local setmetatable = setmetatable
local C_CreatureInfo = C_CreatureInfo

local GetLocale = GetLocale

local L = {}

-- Classes
L["Druid"] = C_CreatureInfo.GetClassInfo(11).className
L["Hunter"] = C_CreatureInfo.GetClassInfo(3).className
L["Mage"] = C_CreatureInfo.GetClassInfo(8).className
L["Paladin"] = C_CreatureInfo.GetClassInfo(2).className
L["Priest"] = C_CreatureInfo.GetClassInfo(5).className
L["Rogue"] = C_CreatureInfo.GetClassInfo(4).className
L["Shaman"] = C_CreatureInfo.GetClassInfo(7).className
L["Warlock"] = C_CreatureInfo.GetClassInfo(9).className
L["Warrior"] = C_CreatureInfo.GetClassInfo(1).className

-- Races
L["Human"] = C_CreatureInfo.GetRaceInfo(1).raceName
L["Orc"] = C_CreatureInfo.GetRaceInfo(2).raceName
L["Dwarf"] = C_CreatureInfo.GetRaceInfo(3).raceName
L["Night Elf"] = C_CreatureInfo.GetRaceInfo(4).raceName
L["Undead"] = C_CreatureInfo.GetRaceInfo(5).raceName
L["Tauren"] = C_CreatureInfo.GetRaceInfo(6).raceName
L["Gnome"] = C_CreatureInfo.GetRaceInfo(7).raceName
L["Troll"] = C_CreatureInfo.GetRaceInfo(8).raceName
L["Blood Elf"] = C_CreatureInfo.GetRaceInfo(10).raceName
L["Draenei"] = C_CreatureInfo.GetRaceInfo(11).raceName

if (GetLocale() == "ruRU") then
    -- Specs
    L["Balance"] = "Баланс"
    L["Feral"] = "Сила зверя"
    L["Restoration"] = "Исцеление"
    L["Beast Mastery"] = "Повелитель зверей"
    L["Marksmanship"] = "Стрельба"
    L["Survival"] = "Выживание"
    L["Arcane"] = "Тайная магия"
    L["Fire"] = "Огонь"
    L["Frost"] = "Лед"
    L["Holy"] = "Свет"
    L["Protection"] = "Защита"
    L["Retribution"] = "Возмездие"
    L["Discipline"] = "Послушание"
    L["Shadow"] = "Тьма"
    L["Assassination"] = "Ликвидация"
    L["Combat"] = "Бой"
    L["Subtlety"] = "Скрытность"
    L["Elemental"] = "Cтихии"
    L["Enhancement"] = "Совершенствование"
    L["Affliction"] = "Колдовство"
    L["Demonology"] = "Демонология"
    L["Destruction"] = "Разрушение"
    L["Arms"] = "Оружие"
    L["Fury"] = "Неистовство"

    -- Gladdy.lua
    L["Welcome to Gladdy!"] = "Вас приветствует Gladdy!"
    L["First run has been detected, displaying test frame."] = "Обнаружен первый запуск, показываем тестовое окно."
    L["Valid slash commands are:"] = "Валидные команды:"
    L["If this is not your first run please lock or move the frame to prevent this from happening."] = "Если это не первый запуск, переместите, либо закрепите окно во избежание показа окна."

    -- Frame.lua
    L["Gladdy - drag to move"] = "Gladdy - тащите для перемещения"

    -- Options.lua
    L["Announcements"] = "Оповещения"
    L["Announcement settings"] = "Настройки оповещения"
    L["Auras"] = "Ауры"
    L["Auras settings"] = "Настройки аур"
    L["Castbar"] = "Полоса применения"
    L["Castbar settings"] = "Настройки полосы применения"
    L["Classicon"] = "Иконка класса"
    L["Classicon settings"] = "Настройки иконки класса"
    L["Clicks"] = "Клики"
    L["Clicks settings"] = "Настройки кликов"
    L["Diminishings"] = "Диминишинги"
    L["Diminishings settings"] = "Настройки диминишингов"
    L["Healthbar"] = "Полоса жизней"
    L["Healthbar settings"] = "Настройки полосы жизней"
    L["Highlight"] = "Подсветка"
    L["Highlight settings"] = "Настройки подсветки"
    L["Nameplates"] = "Индикаторы здоровья"
    L["Nameplates settings"] = "Настройки индикаторов здоровья "
    L["Powerbar"] = "Полоса маны"
    L["Powerbar settings"] = "Настройки полосы маны"
    L["Score"] = "Счет"
    L["Score settings"] = "Настройки счета"
    L["Trinket"] = "Тринкет"
    L["Trinket settings"] = "Настройки тринкета"
    L["Reset module"] = "Сбросить настройки"
    L["Reset module to defaults"] = "Сбросить настройки модуля к начальным"
    L["No settings"] = "Нет настроек"
    L["Module has no settings"] = "Модуль не имеет настроек"
    L["General"] = "Основные"
    L["General settings"] = "Основные настройки"
    L["Lock frame"] = "Закрепить фрейм"
    L["Toggle if frame can be moved"] = "Включите, если фрейм можно двигать"
    L["Grow frame upwards"] = "Расти вверх"
    L["If enabled the frame will grow upwards instead of downwards"] = "Если включено, то фрейм будет расти вверх, а не вниз"
    L["Frame scale"] = "Масштаб фрейма"
    L["Scale of the frame"] = "Масштаб фрейма"
    L["Frame padding"] = "Отступы фрейма"
    L["Padding of the frame"] = "Отступы фрейма"
    L["Frame color"] = "Цвет фрейма"
    L["Color of the frame"] = "Цвет фрейма"
    L["Bar width"] = "Ширина полос"
    L["Width of the bars"] = "Ширина полос"
    L["Bottom margin"] = "Нижняя граница полосы"
    L["Margin between each button"] = "Отступ до следующей полосы"

    -- Announcements.lua
    L["RESURRECTING: %s (%s)"] = "ВОСКРЕШАЕТ: %s (%s)"
    L["SPEC DETECTED: %s - %s (%s)"] = "СПЕЦИАЛИЗАЦИЯ ОПРЕДЕЛЕНА: %s - %s (%s)"
    L["LOW HEALTH: %s (%s)"] = "МАЛО ЗДОРОВЬЯ: %s (%s)"
    L["TRINKET USED: %s (%s)"] = "ТРИНКЕТ ИСПОЛЬЗОВАН: %s (%s)"
    L["TRINKET READY: %s (%s)"] = "ТРИНКЕТ ГОТОВ: %s (%s)"
    L["DRINKING: %s (%s)"] = "ПЬЁТ: %s (%s)"
    L["Self"] = "Сам"
    L["Party"] = "Группа"
    L["Raid Warning"] = "Объявление рейду"
    L["Blizzard's Floating Combat Text"] = "Стандартный текст боя"
    L["MikScrollingBattleText"] = "MikScrollingBattleText"
    L["Scrolling Combat Text"] = "Scrolling Combat Text"
    L["Parrot"] = "Parrot"
    L["Drinking"] = "Питьё"
    L["Announces when enemies sit down to drink"] = "Оповещать, когда вражеский игрок начинает пить"
    L["Resurrection"] = "Воскрешение"
    L["Announces when an enemy tries to resurrect a teammate"] = "Оповещать, когда вражеский игрок начинает воскрешать союзника"
    L["New enemies"] = "Новые враги"
    L["Announces when new enemies are discovered"] = "Оповещать о найденных вражеских игроках"
    L["Spec Detection"] = "Обнаружение специализации"
    L["Announces when the spec of an enemy was detected"] = "Оповещать, когда обнаружена специализация вражеского игрока"
    L["Low health"] = "Мало жизней"
    L["Announces when an enemy drops below a certain health threshold"] = "Оповещать, когда уровень здоровья вражеского игрока падает ниже определенного количества"
    L["Low health threshold"] = "Процент малого количества здоровья"
    L["Choose how low an enemy must be before low health is announced"] = "Укажите процент здоровья вражеского игрока, когда нужно показать оповещение"
    L["Trinket used"] = "Использование пвп-тринкета"
    L["Announce when an enemy's trinket is used"] = "Оповещать об использовании пвп-тринкета вражеским игроком"
    L["Trinket ready"] = "Готовность пвп-тринкета"
    L["Announce when an enemy's trinket is ready again"] = "Оповещать, когда пвп-тринкет вражеского игрока готов"
    L["Destination"] = "Вариант оповещений"
    L["Choose how your announcements are displayed"] = "Выберать, как показывать оповещения"

    -- Auras.lua
    L["Font color"] = "Цвет текста"
    L["Color of the text"] = "Цвет текста"
    L["Font size"] = "Размер текста"
    L["Size of the text"] = "Размер текста"

    -- Castbar.lua
    L["Bar height"] = "Высота полосы"
    L["Height of the bar"] = "Высота полосы"
    L["Bar texture"] = "Текстура полосы"
    L["Texture of the bar"] = "Текстура полосы"
    L["Bar color"] = "Цвет полосы"
    L["Color of the cast bar"] = "Цвет полосы применений"
    L["Background color"] = "Цвет фона полосы"
    L["Color of the cast bar background"] = "Цвет фона полосы применений"
    L["Icon position"] = "Расположение значка трансляции"

    -- Diminishings.lua
    L["DR Cooldown position"] = "Позиция ДР таймеров"
    L["Position of the cooldown icons"] = "Позиция ДР таймеров"
    L["Left"] = "Слева"
    L["Right"] = "Справа"
    L["Icon Size"] = "Размер иконок"
    L["Size of the DR Icons"] = "Размер ДР иконок"

    -- Healthbar.lua
    L["Show the actual health"] = "Показывать текущее здоровье"
    L["Show the actual health on the health bar"] = "Показывать текущее здоровье на полосе жизней"
    L["Show max health"] = "Показывать максимальное здоровье"
    L["Show max health on the health bar"] = "Показывать максимальное здоровье на полосе жизней"
    L["Show health percentage"] = "Показывать здоровье в процентах"
    L["Show health percentage on the health bar"] = "Показывать здоровье в процентах на полосе жизней"

    -- Highlight.lua
    L["Border size"] = "Размер границы"
    L["Target border color"] = "Цвет контура цели"
    L["Color of the selected targets border"] = "Цвет контура цели"
    L["Focus border color"] = "Цвет контура фокуса"
    L["Color of the focus border"] = "Цвет контура фокуса"
    L["Raid leader border color"] = "Цвет контура цели рейд лидера"
    L["Color of the raid leader border"] = "Цвет контура цели рейд лидера"
    L["Highlight target"] = "Подсвечивать цель"
    L["Toggle if the selected target should be highlighted"] = "Включите, если необходима подсветка цели"
    L["Show border around target"] = "Показывать контур вокруг цели"
    L["Toggle if a border should be shown around the selected target"] = "Включите, если необходимо показывать контур вокруг цели"
    L["Show border around focus"] = "Показывать контур вокруг фокуса"
    L["Toggle of a border should be shown around the current focus"] = "Включите, если необходимо показывать контур вокруг фокуса"
    L["Show border around raid leader"] = "Показывать контур вокруг цели рейд лидера"
    L["Toggle if a border should be shown around the raid leader"] = "Включите, если необходимо показывать контур вокруг цели рейд лидера"

    -- Powerbar.lua
    L["Show the actual power"] = "Показывать текущую ману"
    L["Show the actual power on the power bar"] = "Показывать текущую ману на полосе маны"
    L["Show max power"] = "Показывать максимальную ману"
    L["Show max power on the power bar"] = "Показывать максимальную ману на полосе маны"
    L["Show power percentage"] = "Показывать ману в процентах"
    L["Show power percentage on the power bar"] = "Показывать ману в процентах на полосе маны"
    L["Color of the status bar background"] = "Цвет фона строки состояния"

    -- Trinket.lua
    L["No cooldown count (OmniCC)"] = "Не показывать кулдаун (OmniCC)"
    L["Disable cooldown timers by addons (reload UI to take effect)"] = "Отключить таймер кулдаунов для аддонов (необходима перезагрузка интерфейса)"
elseif GetLocale() == "deDE" then
    -- Announcements.lua
    L["Announcements"] = "Meldungen"
    L["RESURRECTING: %s (%s)"] = "Wiederbeleben: %s (%s) "
    L["SPEC DETECTED: %s - %s (%s)"] = "Talenspezalisierung entdeckt: %s - %s (%s)"
    L["LOW HEALTH: %s (%s)"] = "Niedriges Leben: %s (%s)"
    L["TRINKET USED: %s (%s)"] = "Insiginie benutzt: %s (%s)"
    L["TRINKET READY: %s (%s)"] = "Insignie bereit: %s (%s)"
    L["DRINKING: %s (%s)"] = "Trinken: %s (%s)"
    L["Self"] = "Selbst"
    L["Party"] = "Gruppe"
    L["Raid Warning"] = "Schlachtzugwarnung"
    L["Blizzard's Floating Combat Text"] = "Blizzard Kampftext"
    L["Trinket used"] = "Insignie benutzt"
    L["Announce when an enemy's trinket is used"] = "Warnt, wenn ein Gegner seine Insignie benutzt"
    L["Trinket ready"] = "Insignie bereit"
    L["Announce when an enemy's trinket is ready again"] = "Warnt wenn die Insignie eines Gegner wieder bereit ist"
    L["Drinking"] = "Trinken"
    L["Announces when enemies sit down to drink"] = "Warnt wenn Gegner sich zum Trinken hinsetzen"
    L["Resurrection"] = "Wiederbelebung"
    L["Announces when an enemy tries to resurrect a teammate"] = "Warnt wenn Gegner versuchen Teammitglieder wiederzubeleben"
    L["New enemies"] = "Neue Gegner"
    L["Announces when new enemies are discovered"] = "Gibt an, wenn neue Gegner entdeckt wurden"
    L["Spec Detection"] = "Talent Entdeckung"
    L["Announces when the spec of an enemy was detected"] = "Gibt an, wenn Talente eines Gegners entdeckt wurden"
    L["Low health"] = "Wenig Leben"
    L["Announces when an enemy drops below a certain health threshold"] = "Warnt, wenn das Leben eines Gegners unter einen bestimmten Prozentwert fällt"
    L["Low health threshold"] = "Prozentwert: Wenig Leben"
    L["Choose how low an enemy must be before low health is announced"] = "Bestimme wie wenig Leben ein Gegner haben muss, damit vor wenig Leben gewarnt wird"
    L["Destination"] = "Ziel"
    L["Choose how your announcements are displayed"] = "Bestimme wo Warnungen dargestellt werden"

    -- ArenaCountDown.lua
    L["Arena Countdown"] = "Arena Countdown"
    L["Turns countdown before the start of an arena match on/off."] = ""
    L["Size"] = "Größe"

    -- Auras.lua
    L["Auras"] = "Auren"
    L["Frame"] = "Frame"
    L["Cooldown"] = "Abklingzeit"
    L["No Cooldown Circle"] = "Verstecke Abklingzeitzirkel"
    L["Cooldown circle alpha"] = "Abklingzeitzirkel Alpha"
    L["Font"] = "Schrift"
    L["Font of the cooldown"] = "Schrift der Abklingzeit"
    L["Font scale"] = "Schriftskalierung"
    L["Scale of the text"] = "Skalierungfaktor des Texts"
    L["Font color"] = "Schriftfarbe"
    L["Color of the text"] = "Farbe des Texts"
    L["Border"] = "Rahmen"
    L["Border style"] = "Rahmen Stil"
    L["Buff color"] = "Buff Farbe"
    L["Debuff color"] = "Debuff Farbe"
    L["Check All"] = "Alle auswählen"
    L["Uncheck All"] = "Alle abwählen"
    L["Enabled"] = "Eingeschaltet"
    L["Priority"] = "Priorität"

    -- BuffsDebuffs.lua
    L["Buffs and Debuffs"] = "Buffs und Debuffs"
    L["Enabled Buffs and Debuffs module"] = "Buffs und Debuffs Modul einschalten"
    L["Show CC"] = "Zeige Crowdcontrol"
    L["Shows all debuffs, which are displayed on the ClassIcon as well"] = "Zeigt alle Buffs & Debuffs, die auch auf dem Klassensymbol dargestellt werden"
    L["Buffs"] = "Buffs"
    L["Size & Padding"] = "Größe und Abstand"
    L["Icon Size"] = "Symbol Größe"
    L["Size of the DR Icons"] = "Größe der DR Symbole"
    L["Icon Width Factor"] = "Symbol Breitenfaktor"
    L["Stretches the icon"] = "Streckt das Symbol"
    L["Icon Padding"] = "Symbol Abstand"
    L["Space between Icons"] = "Abstand zwischen den Symbolen"
    L["Position"] = "Position"
    L["Aura Position"] = "Aura Position"
    L["Position of the aura icons"] = "Position der Aura Symbole"
    L["Top"] = "Oben"
    L["Bottom"] = "Unten"
    L["Left"] = "Links"
    L["Right"] = "Rechts"
    L["Grow Direction"] = "Richtung"
    L["Grow Direction of the aura icons"] = "In welche Richtung die Symbole wachsen"
    L["Horizontal offset"] = "Horizontaler Offset"
    L["Vertical offset"] = "Vertikaler Offset"
    L["Alpha"] = "Alpha"
    L["Debuffs"] = "Debuffs"
    L["Dynamic Timer Color"] = "Dynamische Textfarbe"
    L["Show dynamic color on cooldown numbers"] = "Verändert die Farbe des Textes dynamisch"
    L["Color of the cooldown timer and stacks"] = "Farbe der Abklingzeit und Stapel"
    L["Spell School Colors"] = "Zauberart Farbe"
    L["Spell School Colors Enabled"] = "Zauberart Farbe Eingeschaltet"
    L["Show border colors by spell school"] = "Färbt den Rahmen entspechend der Zauberart"
    L["Curse"] = "Fluch"
    L["Color of the border"] = "Farbe des Rahmens"
    L["Magic"] = "Magie"
    L["Poison"] = "Gift"
    L["Physical"] = "Physisch"
    L["Immune"] = "Immun"
    L["Disease"] = "Erkrankung"
    L["Aura"] = "Aura"
    L["Form"] = "Form"

    -- Castbar.lua
    L["Cast Bar"] = "Zauberleiste"
    L["Bar"] = "Balken"
    L["Bar Size"] = "Balken Größe"
    L["Bar height"] = "Balken Höhe"
    L["Height of the bar"] = "Höhe des Balken"
    L["Bar width"] = "Balken Weite"
    L["Width of the bars"] = "Weite des Balken"
    L["Texture"] = "Textur"
    L["Bar texture"] = "Balken Textur"
    L["Texture of the bar"] = "Textur des Balken"
    L["Bar color"] = "Balken Farbe"
    L["Color of the cast bar"] = "Farbe des Balken"
    L["Background color"] = "Hintergrundfarbe"
    L["Color of the cast bar background"] = "Hinergrundfarbe des Zauberbalkens"
    L["Border size"] = "Rahmen Größe"
    L["Status Bar border"] = "Balken Rahmen"
    L["Status Bar border color"] = "Balken Rahmen Farbe"
    L["Icon"] = "Symbol"
    L["Icon size"] = "Symbolgröße"
    L["Icon border"] = "Symbolrahmen"
    L["Icon border color"] = "Farbe Symbolrahmen"
    L["Spark"] = "Funke"
    L["Spark enabled"] = "Funke eingeschaltet"
    L["Spark color"] = "Funkenfarbe"
    L["Color of the cast bar spark"] = "Farbe des Zauberleisten Funke"
    L["Font of the castbar"] = "Schriftart der Zauberleiste"
    L["Font size"] = "Schriftgröße"
    L["Size of the text"] = "Schriftgröße"
    L["Format"] = "Darstellung"
    L["Timer Format"] = "Zeitdarstellung"
    L["Remaining"] = "Verbleibend"
    L["Total"] = "Total"
    L["Both"] = "Beides"
    L["Castbar position"] = "Zauberleistenposition"
    L["Icon position"] = "Symbolposition"
    L["Offsets"] = "Offsets"

    -- Classicon.lua
    L["Class Icon"] = "Klassensymbol"
    L["Balance"] = "Gleichgewicht"
    L["Feral"] = "Wilder Kampf"
    L["Restoration"] = "Wiederherstellung"
    L["Beast Mastery"] = "Tierherrschaft"
    L["Marksmanship"] = "Treffsicherheit"
    L["Survival"] = "Überleben"
    L["Arcane"] = "Arkan"
    L["Fire"] = "Feuer"
    L["Frost"] = "Frost"
    L["Holy"] = "Heilig"
    L["Protection"] = "Schutz"
    L["Retribution"] = "Vergeltung"
    L["Discipline"] = "Disziplin"
    L["Shadow"] = "Schatten"
    L["Assassination"] = "Meucheln"
    L["Combat"] = "Kampf"
    L["Subtlety"] = "Täuschung"
    L["Elemental"] = "Elemental"
    L["Enhancement"] = "Verstärkung"
    L["Affliction"] = "Gebrechen"
    L["Demonology"] = "Demonologie"
    L["Destruction"] = "Zerstörung"
    L["Arms"] = "Waffen"
    L["Fury"] = "Furor"
    L["Show Spec Icon"] = "Zeige Spezialisierungssymbol"
    L["Shows Spec Icon once spec is detected"] = "Zeigt das Talentspezialisierungs Symbol sobald die Spezialisierung erkannt wurde"
    L["Icon width factor"] = "Symbol Breitenfaktor"
    L["This changes positions with trinket"] = "Das tauscht die Position mit dem Trinket, wenn auf der gleichen Seite."
    L["Border color"] = "Rahmenfarbe"

    --CombatIndicator.lua
    L["Combat Indicator"] = "Kampfindikator"
    L["Enable Combat Indicator icon"] = "Schalte Kampfindikator ein"
    L["Anchor"] = "Anker"
    L["This changes the anchor of the ci icon"] = "Dies ändert den Anker des Kampfindikatorsymbols"
    L["This changes position relative to its anchor of the ci icon"] = "Dies ändert die Position relativ zum Anker"

    -- Cooldowns.lua
    L["Cooldowns"] = "Abklingzeiten"
    L["Enabled cooldown module"] = ""
    L["Cooldown size"] = "Abklingzeit Größe"
    L["Size of each cd icon"] = "Größe eines einzelnen Symbols"
    L["Max Icons per row"] = "Maximale Anzahl an Symbolen pro Reihe"
    L["Scale of the font"] = "Skalierung der Schrift"
    L["Anchor of the cooldown icons"] = "Anker der Abklingzeiten Symbole"
    L["Grow Direction of the cooldown icons"] = "Richtung der Abklingzeiten Symbole"
    L["Offset"] = "Offset"

    -- Diminishings.lua
    L["Diminishings"] = "DR"
    L["Enabled DR module"] = "DR einschalten"
    L["DR Cooldown position"] = "DR Position"
    L["Position of the cooldown icons"] = "Position der Symbole"
    L["DR Border Colors"] = "DR Rahmen Farbe"
    L["Dr Border Colors Enabled"] = "DR Rahmen Farben eingeschaltet"
    L["Colors borders of DRs in respective DR-color below"] = "Färbt die Rahmen der DR Symbole je nach Stärke der Verminderung"
    L["Half"] = "Hälfte"
    L["Quarter"] = "Viertel"
    L["Categories"] = "Kategorien"
    L["Force Icon"] = "Erzwinge Symbol"
    L["Icon of the DR"] = "Symbol des DR"
    L["DR Duration"] = "DR Dauer"
    L["Change the DR Duration in seconds (DR is dynamic between 15-20s)"] = "Verändere die DR Dauer in Sekunden (DR ist dynamisch zwischen 15-20s)"

    -- ExportImport.lua
    L["Export Import"] = "Exportieren Importieren"
    L["Profile Export Import"] = "Profile Exportieren Importieren"

    -- Healthbar.lua
    L["Health Bar"] = "Lebensbalken"
    L["DEAD"] = "TOT"
    L["LEAVE"] = "VERLASSEN"
    L["General"] = "Allgemein"
    L["Color of the status bar background"] = "Farbe des Balkenhintergrunds"
    L["Font of the bar"] = "Schriftart des Balken"
    L["Name font size"] = "Schriftgröße des Namen"
    L["Size of the name text"] = "Schriftgröße des Namen"
    L["Health font size"] = "Schriftgröße der Gesundheit"
    L["Size of the health text"] = "Schriftgröße der Gesundheit"
    L["Size of the border"] = "Rahmengröße"
    L["Health Bar Text"] = "Lebensbalken Text"
    L["Show name text"] = "Namen zeigen"
    L["Show the units name"] = "Zeige den Namen des Gegners"
    L["Show ArenaX"] = "ArenaX zeigen"
    L["Show 1-5 as name instead"] = "Zeigt 1-5 anstatt des Namens"
    L["Show the actual health"] = "Zeige die momentane Gesundheit"
    L["Show the actual health on the health bar"] = "Zeigt die momentane Gesundheit"
    L["Show max health"] = "Zeige maximale Gesundheit"
    L["Show max health on the health bar"] = "Zeige maximale Gesundheit"
    L["Show health percentage"] = "Zeige Prozentwert"
    L["Show health percentage on the health bar"] = "Zeige Prozentwert der Gesundheit"

    -- Highlight.lua
    L["Highlight"] = "Hervorhebung"
    L["Show Inside"] = "Zeige innen"
    L["Show Highlight border inside of frame"] = "Zeige die Hervorhebung innerhalb des Frames"
    L["Colors"] = "Farben"
    L["Target border color"] = "Rahmenfarbe deines Ziels"
    L["Color of the selected targets border"] = "Rahmenfarbe deines momentanen Ziels"
    L["Focus border color"] = "Rahmenfarbe deines Fokus"
    L["Color of the focus border"] = "Rahmenfarbe deines momentanen Fokus"
    L["Highlight target"] = "Hervorhebung des Ziels"
    L["Toggle if the selected target should be highlighted"] = "Ziel hervorheben ein/ausschalten"
    L["Show border around target"] = "Zeige Rahmen um dein Ziel"
    L["Toggle if a border should be shown around the selected target"] = "Zeigt Rahmen um dein momentanes Ziel"
    L["Show border around focus"] = "Zeige Rahmen um dein Fokus"
    L["Toggle of a border should be shown around the current focus"] = "Zeigt Rahmen um dein Fokusziel"

    -- Pets.lua
    L["Pets"] = "Begleiter"
    L["Enables Pets module"] = "Schaltet das Begleiter Modul ein"
    L["Width of the bar"] = "Breite des Balkens"
    L["Health color"] = "Gesundheitsfarbe"
    L["Color of the status bar"] = "Farbe des Balkens"
    L["Portrait"] = "Portrait"
    L["Health Values"] = "Gesundheitswerte"

    -- Powerbar.lua
    L["Power Bar"] = "Mana/Energie Balken"
    L["Power Bar Text"] = "Mana/Energie Balken Text"
    L["Power Texts"] = "Mana/Energie Balken Texte"
    L["Show race"] = "Rasse zeigen"
    L["Show spec"] = "Spezialisierung zeigen"
    L["Show the actual power"] = "Zeige das momentane Mana"
    L["Show the actual power on the power bar"] = "Zeige das momentane Mana"
    L["Show max power"] = "Zeige das maximale Mana"
    L["Show max power on the power bar"] = "Zeige das maximale Mana"
    L["Show power percentage"] = "Zeige Prozentwert"
    L["Show power percentage on the power bar"] = "Zeige Prozentwert"

    -- Racial.lua
    L["Racial"] = "Rassenfertigkeit"
    L["Enable racial icon"] = "Rassenfertigkeit einschalten"
    L["This changes the anchor of the racial icon"] = "Dies ändert den Anker des Rassenfertigkeitssymbols"
    L["This changes position relative to its anchor of the racial icon"] = "Dies ändert doe Position relativ zu seinem Anker"

    -- TotemPlates.lua
    L["Totem Plates"] = "Totem Symbole"
    L["Customize Totems"] = "Individuelle Totemeinstellungen"
    L["Custom totem name"] = "Individueller Totem Name"
    L["Totem General"] = "Totems Allgemein"
    L["Turns totem icons instead of nameplates on or off. (Requires reload)"] = ""
    L["Show friendly"] = "Zeige für freundliche"
    L["Show enemy"] = "Zeige für feindliche"
    L["Totem size"] = "Totem Größe"
    L["Size of totem icons"] = "Größe der Totemsymbole"
    L["Font of the custom totem name"] = "Schriftart der benutzerdefinierten Totem Namen"
    L["Apply alpha when no target"] = "Wende den Alpha-Wert an, wenn kein Ziel anvisiert ist"
    L["Always applies alpha, even when you don't have a target. Else it is 1."] = "Alpha immer anwenden, auch wenn man kein Ziel anvisiert hat. Sonst ist der Alpha-Wert 1"
    L["Apply alpha when targeted"] = "Wende den Alpha-Wert an, wenn das Totem als Ziel anvisiert ist"
    L["Always applies alpha, even when you target the totem. Else it is 1."] = "Alpha immer anwenden, auch wenn das Totem als Ziel anvisiert ist. Sonst ist der Alpha-Wert 1"
    L["All totem border alphas (configurable per totem)"] = "Alpha aller Totems"
    L["Totem icon border style"] = "Totem Rahmenstil"
    L["All totem border color"] = "Rahmenfarbe aller Totems"

    -- Trinket.lua
    L["Trinket"] = "Insignie"
    L["Enable trinket icon"] = "Insignie einschalten"
    L["This changes positions of the trinket"] = "Dies ändert die Position der Insignie"

    -- XiconProfiles.lua
    L["Profile"] = "Profil"

    -- Frame.lua
    L["Gladdy - drag to move"] = "Gladdy - ziehe um zu bewegen"

    -- Gladdy.lua
    L["Welcome to Gladdy!"] = "Willkommen bei Gladdy!"
    L["First run has been detected, displaying test frame."] = "Erster Start wurde entdeckt, zeige Testbild an."
    L["Valid slash commands are:"] = "Gültige slash Befehle sind:"
    L["If this is not your first run please lock or move the frame to prevent this from happening."] = "Wenn dies nicht dein erster Start ist, sperre oder bewege das Bild um diese Meldung zu verhindern."

    -- Options.lua
    L["settings"] = "Einstellungen"
    L["Reset module"] = "Modul zurücksetzen"
    L["Reset module to defaults"] = "Setze das Modul auf seine Standardwerte zurück"
    L["No settings"] = "Keine Einstellungen"
    L["Module has no settings"] = "Modul hat keine Einstellungen"
    L["General settings"] = "Allgemeine Einstellungen"
    L["Lock frame"] = "Sperre Frame"
    L["Toggle if frame can be moved"] = "Aktivieren falls das Frame bewegt werden kann"
    L["Grow frame upwards"] = "Frame von unten nach oben aufbauen"
    L["If enabled the frame will grow upwards instead of downwards"] = "Falls aktiviert, wird das Frame von unten nach oben aufgebaut"
    L["Down"] = "Runter"
    L["Up"] = "Hoch"
    L["Frame General"] = "Frame Allgemein"
    L["Frame scale"] = "Frame Skalierung"
    L["Scale of the frame"] = "Skalierung des Frames"
    L["Frame padding"] = "Symbolabstand"
    L["Padding of the frame"] = "Abstand zwischen den Elementen des Frames"
    L["Frame width"] = "Frame Breite"
    L["Margin"] = "Frame Abstand"
    L["Margin between each button"] = "Abstand zwischen den Arena Einheiten"
    L["Cooldown General"] = "Abklingzeiten Allgemein"
    L["Font General"] = "Schriftart Allgemein"
    L["General Font"] = "Allgemeine Schriftart"
    L["Font color text"] = "Schriftfarbe von text"
    L["Font color timer"] = "Schriftfarbe von Abklingzeiten"
    L["Color of the timers"] = "Farbe der Abklingzeiten"
    L["Icons General"] = "Symbol Allgemein"
    L["Icon border style"] = "Rahmenstil"
    L["This changes the border style of all icons"] = "Dies ändert den Rahmenstil aller Symbole"
    L["This changes the border color of all icons"] = "Dies ändert die Rahmenfarbe aller Symbole"
    L["Statusbar General"] = "Balken Allgemein"
    L["Statusbar texture"] = "Balken Textur"
    L["This changes the texture of all statusbar frames"] = "Dies ändert die Textur aller Balken"
    L["Statusbar border style"] = "Balken Rahmenstil"
    L["This changes the border style of all statusbar frames"] = "Dies ändert den Rahmenstil aller Balken"
    L["Statusbar border offset divider (smaller is higher offset)"] = "Rahmenstil offset Quotient"
    L["Offset of border to statusbar (in case statusbar shows beyond the border)"] = "Offset des Rahmens zur Statusbar (falls der Balken hinter dem Rahmen erscheint)"
    L["Statusbar border color"] = "Balken Rahmenfarbe"
    L["This changes the border color of all statusbar frames"] = "Dies ändert die Rahmenfarbe aller Balken"
elseif GetLocale() == "zhTW" then
    -- Announcements.lua
    L["Announcements"] = "通報"
    L["RESURRECTING: %s (%s)"] = "復活: %s (%s) "
    L["SPEC DETECTED: %s - %s (%s)"] = "敵方天賦: %s - %s (%s)"
    L["LOW HEALTH: %s (%s)"] = "低生命值: %s (%s)"
    L["TRINKET USED: %s (%s)"] = "飾品已使用: %s (%s)"
    L["TRINKET READY: %s (%s)"] = "飾品就緒: %s (%s)"
    L["DRINKING: %s (%s)"] = "正在喝水: %s (%s)"
    L["Self"] = "玩家"
    L["Party"] = "隊伍"
    L["Raid Warning"] = "團隊警告"
    L["Blizzard's Floating Combat Text"] = "Blizzard 戰鬥浮動文字"
    L["Trinket used"] = "飾品已使用"
    L["Announce when an enemy's trinket is used"] = "當敵方使用飾品時發出通知"
    L["Trinket ready"] = "飾品就緒"
    L["Announce when an enemy's trinket is ready again"] = "當敵方飾品就緒時發出通報"
    L["Drinking"] = "正在喝水"
    L["Announces when enemies sit down to drink"] = "當敵方喝水時發出通報"
    L["Resurrection"] = "復活"
    L["Announces when an enemy tries to resurrect a teammate"] = "當敵方嘗試復活隊友時發出通報"
    L["New enemies"] = "新的敵人"
    L["Announces when new enemies are discovered"] = "當發現新的敵人時發出通報"
    L["Spec Detection"] = "天賦偵測"
    L["Announces when the spec of an enemy was detected"] = "當偵測到敵方天賦時發出通報"
    L["Low health"] = "低生命值"
    L["Announces when an enemy drops below a certain health threshold"] = "當敵方生命值低於一定條件時發出通報"
    L["Low health threshold"] = "低生命值門檻"
    L["Choose how low an enemy must be before low health is announced"] = "設定低生命值通報門檻"
    L["Destination"] = "發送通報至"
    L["Choose how your announcements are displayed"] = "選擇通報發送至哪個頻道"

    -- ArenaCountDown.lua
    L["Arena Countdown"] = "競技場計時"
    L["Turns countdown before the start of an arena match on/off."] = "在競技場開始前倒數剩餘秒數"
    L["Size"] = "大小"

    -- Auras.lua
    L["Auras"] = "光環"
    L["Frame"] = "框架"
    L["Cooldown"] = "冷卻時間"
    L["No Cooldown Circle"] = "取消圖示冷卻倒數陰影"
    L["Cooldown circle alpha"] = "冷卻倒數陰影alpha值"
    L["Font"] = "字型"
    L["Font of the cooldown"] = "設定冷卻時間字型"
    L["Font scale"] = "字體大小"
    L["Scale of the text"] = "設定字體大小"
    L["Font color"] = "字體顏色"
    L["Color of the text"] = "設定字體顏色"
    L["Border"] = "邊框"
    L["Border style"] = "邊框樣式"
    L["Buff color"] = "增益顏色"
    L["Debuff color"] = "減益顏色"
    L["Check All"] = "全選"
    L["Uncheck All"] = "取消全選"
    L["Enabled"] = "啟用"
    L["Priority"] = "優先"
    L["Interrupt Spells School Colors"] = "打斷法術分類顏色"
    L["Enable Interrupt Spell School Colors"] = "啟用"
    L["Will use Debuff Color if disabled"] = "若未啟用則使用一般減益顏色"
    L["Buffs"] = "增益" --Line 573
    L["Debuffs"] = "減益" --Line 566
    L["Interrupts"] = "斷法" --Line 580

    -- BuffsDebuffs.lua
    L["Buffs and Debuffs"] = "增益與減益"
    L["Enabled Buffs and Debuffs module"] = "啟用增益與減益模組"
    L["Show CC"] = "顯示控場"
    L["Shows all debuffs, which are displayed on the ClassIcon as well"] = "顯示所有減益效果，這些減益效果也顯示在職業圖示上"
    L["Buffs"] = "增益"
    L["Size & Padding"] = "大小與內距"
    L["Icon Size"] = "圖示大小"
    L["Size of the DR Icons"] = "遞減圖示大小"
    L["Icon Width Factor"] = "圖示寬度比例"
    L["Stretches the icon"] = "圖示寬度"
    L["Icon Padding"] = "圖示內距"
    L["Space between Icons"] = "圖示間距"
    L["Position"] = "位置"
    L["Aura Position"] = "光環位置"
    L["Position of the aura icons"] = "光環圖示位置"
    L["Top"] = "頂部"
    L["Bottom"] = "底部"
    L["Left"] = "左"
    L["Right"] = "右"
    --L["Grow Direction"] = ""
    L["Grow Direction of the aura icons"] = "光環圖示的延伸方向"
    L["Horizontal offset"] = "水平位移"
    L["Vertical offset"] = "垂直位移"
    L["Alpha"] = "Alpha值"
    L["Debuffs"] = "減益"
    L["Dynamic Timer Color"] = "動態計時條顏色"
    L["Show dynamic color on cooldown numbers"] = "冷卻時間數字以動態顏色顯示"
    L["Color of the cooldown timer and stacks"] = "Farbe der Abklingzeit und Stapel"
    L["Spell School Colors"] = "法術種類顏色"
    L["Spell School Colors Enabled"] = "啟用"
    L["Show border colors by spell school"] = "根據不同法術種類顯示不同邊框顏色"
    L["Curse"] = "詛咒"
    L["Color of the border"] = "邊框顏色"
    L["Magic"] = "魔法"
    L["Poison"] = "中毒"
    L["Physical"] = "物理"
    L["Immune"] = "免疫"
    L["Disease"] = "疾病"
    L["Aura"] = "光環"
    L["Form"] = "形態"
    L["Font"] = "字型" --Line 906
    L["Border"] = "邊框" --Line 949
    L["Debuff Lists"] = "減益列表" --Line 1036
    L["Buff Lists"] = "增益列表" --Line 1051

    -- Castbar.lua
    L["Cast Bar"] = "施法條"
    L["Bar"] = "施法條"
    L["Bar Size"] = "施法條大小"
    L["Bar height"] = "高度"
    L["Height of the bar"] = "計量條高度"
    L["Bar width"] = "寬度"
    L["Width of the bars"] = "計量條寬度"
    L["Texture"] = "材質"
    L["Bar texture"] = "施法條材質"
    L["Texture of the bar"] = "計量條材質"
    L["Bar color"] = "施法條顏色"
    L["Color of the cast bar"] = "計量條顏色"
    L["Background color"] = "背景顏色"
    L["Color of the cast bar background"] = "施法條背景顏色"
    L["Border size"] = "邊框大小"
    L["Status Bar border"] = "狀態列邊框"
    L["Status Bar border color"] = "狀態列邊框顏色"
    L["Icon"] = "圖示"
    L["Icon size"] = "圖示大小"
    L["Icon border"] = "圖示邊框"
    L["Icon border color"] = "圖示邊框顏色"
    L["If test is running, type \"/gladdy test\" again"] = "如果測試已經開始，調整此選項後請輸入/gladdy test以重新開始測試"
    L["Spark"] = "尾端發亮"
    L["Spark enabled"] = "啟用"
    L["Spark color"] = "顏色"
    L["Color of the cast bar spark"] = "計時條進度的尾端顏色"
    L["Font of the castbar"] = "施法條字型"
    L["Font size"] = "字體大小"
    L["Size of the text"] = "施法條字體大小"
    L["Format"] = "格式"
    L["Timer Format"] = "時間格式"
    L["Remaining"] = "剩餘時間"
    L["Total"] = "總時間"
    L["Both"] = "兩者"
    L["Castbar position"] = "施法條位置"
    L["Icon position"] = "圖示位置"
    L["Offsets"] = "位移"

    -- Classicon.lua
    L["Class Icon"] = "職業圖示"
    L["Balance"] = "平衡"
    L["Feral"] = "野性"
    L["Restoration"] = "恢復"
    L["Beast Mastery"] = "獸王"
    L["Marksmanship"] = "射擊"
    L["Survival"] = "生存"
    L["Arcane"] = "奧術"
    L["Fire"] = "火焰"
    L["Frost"] = "冰霜"
    L["Holy"] = "神聖"
    L["Protection"] = "防護"
    L["Retribution"] = "懲戒"
    L["Discipline"] = "戒律"
    L["Shadow"] = "暗影"
    L["Assassination"] = "刺殺"
    L["Combat"] = "戰鬥"
    L["Subtlety"] = "敏銳"
    L["Elemental"] = "元素"
    L["Enhancement"] = "增強"
    L["Affliction"] = "痛苦"
    L["Demonology"] = "惡魔"
    L["Destruction"] = "毀滅"
    L["Arms"] = "武器"
    L["Fury"] = "狂怒"
    L["Show Spec Icon"] = "顯示天賦圖示"
    L["Shows Spec Icon once spec is detected"] = "若偵測到天賦則顯示天賦圖示"
    L["Icon width factor"] = "圖示寬度比例"
    L["This changes positions with trinket"] = "調整職業圖示位置"
    L["Border color"] = "邊框顏色"

    --CombatIndicator.lua
    L["Combat Indicator"] = "戰鬥指示器"
    L["Enable Combat Indicator icon"] = "顯示是否進入戰鬥"
    L["Anchor"] = "定位"
    L["This changes the anchor of the ci icon"] = "調整戰鬥指示器圖示定位點"
    L["This changes position relative to its anchor of the ci icon"] = "調整戰鬥指示器位置"

    -- Constants.lua
    L["Physical"] = "物理" --Line 749
    L["Holy"] = "神聖" --Line 750
    L["Fire"] = "火焰" --Line 751
    L["Nature"] = "自然" --Line 752
    L["Frost"] = "冰霜" --Line 753
    L["Shadow"] = "暗影" --Line 754
    L["Arcane"] = "奧術" --Line 755
    L["Unknown"] = "未知" --Line 756

    -- Cooldowns.lua
    L["Cooldowns"] = "技能冷卻監控"
    L["Enabled cooldown module"] = "啟用冷卻時間監控模組"
    L["Cooldown size"] = "大小"
    L["Size of each cd icon"] = "冷卻時間圖示大小"
    L["Icon Width Factor"] = "寬度"
    L["Max Icons per row"] = "每行圖示數量"
    L["Scale of the font"] = "字體大小"
    L["Anchor of the cooldown icons"] = "冷卻圖示定位"
    L["Grow Direction of the cooldown icons"] = "冷卻圖示延伸方向"
    L["Offset"] = "位移"
    L["BloodElf"] = "血精靈"
    L["NightElf"] = "夜精靈"
    L["Scourge"] = "不死族"

    -- Diminishings.lua
    L["Diminishings"] = "控場遞減"
    L["Enabled DR module"] = "啟用遞減模組"
    L["DR Cooldown position"] = "遞減冷卻時間位置"
    L["Position of the cooldown icons"] = "遞減冷卻時間圖示位置"
    L["DR Border Colors"] = "DR邊框顏色"
    L["Dr Border Colors Enabled"] = "啟用"
    L["Colors borders of DRs in respective DR-color below"] = "邊框顏色依遞減設定為以下顏色"
    L["Half"] = "二分之一"
    L["Quarter"] = "四分之一"
    L["Categories"] = "法術列表"
    L["Force Icon"] = "使用自訂圖示"
    L["Icon of the DR"] = "選擇此區圖示取代原始技能圖示"

    -- ExportImport.lua
    L["Export Import"] = "匯出/匯入"
    L["Profile Export Import"] = "設定檔匯出/匯入"
    L["Export"] = "匯出" --Line 138
    L["Export your current profile to share with others or your various accounts."] = "匯出您目前的設定檔" --Line 139
    L["Import"] = "匯入" --Line 162
    L["This will overwrite your current profile!"] = "這將會覆蓋您目前的設定檔" --Line 163

    -- Healthbar.lua
    L["Health Bar"] = "血量條"
    L["DEAD"] = "死亡"
    L["LEAVE"] = "暫離"
    L["General"] = "一般"
    L["Color of the status bar background"] = "狀態列背景顏色"
    L["Font of the bar"] = "字型"
    L["Name font size"] = "名稱字體大小"
    L["Size of the name text"] = "設定名稱字體大小"
    L["Health font size"] = "生命值字體大小"
    L["Size of the health text"] = "設定生命值字體大小"
    L["Size of the border"] = "邊框大小"
    L["Health Bar Text"] = "血量條文字"
    L["Show name text"] = "顯示名稱"
    L["Show the units name"] = "顯示單位名稱"
    L["Show ArenaX"] = "顯示編號"
    L["Show 1-5 as name instead"] = "使用編號1-5代替角色名稱"
    L["Show the actual health"] = "顯示目前生命值"
    L["Show the actual health on the health bar"] = "在血量條上顯示目前生命值"
    L["Show max health"] = "顯示最大生命值"
    L["Show max health on the health bar"] = "在血量條上顯示最大生命值"
    L["Show health percentage"] = "顯示百分比"
    L["Show health percentage on the health bar"] = "在血量條上顯示生命值百分比"

    -- Highlight.lua
    L["Highlight"] = "高亮提示"
    L["Show Inside"] = "顯示在框架內"
    L["Show Highlight border inside of frame"] = "將高亮邊框顯示於框架內側"
    L["Colors"] = "邊框顏色"
    L["Target border color"] = "目標"
    L["Color of the selected targets border"] = "目標的邊框顏色"
    L["Focus border color"] = "專注"
    L["Color of the focus border"] = "專注目標邊框顏色"
    L["Highlight target"] = "高亮目標"
    L["Toggle if the selected target should be highlighted"] = "是否高亮當前目標"
    L["Show border around target"] = "顯示目標邊框"
    L["Toggle if a border should be shown around the selected target"] = "是否顯示當前目標的邊框"
    L["Show border around focus"] = "顯示專注邊框"
    L["Toggle of a border should be shown around the current focus"] = "是否顯示當前專注目標的邊框"

    -- Pets.lua
    L["Pets"] = "寵物"
    L["Enables Pets module"] = "啟用寵物模組"
    L["Width of the bar"] = "寵物列寬度"
    L["Health color"] = "生命值顏色"
    L["Color of the status bar"] = "狀態列顏色"
    L["Portrait"] = "頭像"
    L["Health Values"] = "生命值"

    -- Powerbar.lua
    L["Power Bar"] = "法力/能量條"
    L["Power Bar Text"] = "法力/能量條文字"
    L["Power Texts"] = "法力/能量條文字"
    L["Show race"] = "顯示種族"
    L["Show spec"] = "顯示天賦"
    L["Show the actual power"] = "顯示目前法力/能量"
    L["Show the actual power on the power bar"] = "在計量條中顯示目前法力/能量值"
    L["Show max power"] = "顯示最大法力/能量值"
    L["Show max power on the power bar"] = "在計量條中顯示最大法力/能量值"
    L["Show power percentage"] = "顯示法力/能量百分比"
    L["Show power percentage on the power bar"] = "在計量條中顯示目前法力/能量百分比"

    -- Racial.lua
    L["Racial"] = "種族"
    L["Enable racial icon"] = "啟用種族圖示"
    L["This changes the anchor of the racial icon"] = "調整種族圖示定位點"
    L["This changes position relative to its anchor of the racial icon"] = "調整種族圖示位置"

    -- TotemPlates.lua
    L["Totem Plates"] = "圖騰名條"
    L["Customize Totems"] = "自訂圖騰"
    L["Custom totem name"] = "自訂圖騰名稱"
    L["Totem General"] = "圖騰通用設定"
    L["Turns totem icons instead of nameplates on or off. (Requires reload)"] = "是否顯示圖騰名條(需重新載入)"
    L["Show friendly"] = "顯示友方圖騰"
    L["Show enemy"] = "顯示敵方圖騰"
    L["Totem size"] = "圖騰大小"
    L["Size of totem icons"] = "圖騰圖示大小"
    L["Font of the custom totem name"] = "自訂圖騰字型"
    L["Apply alpha when no target"] = "圖騰非目標時套用alpha值"
    L["Always applies alpha, even when you don't have a target. Else it is 1."] = "若圖騰未被選為目標，其圖示套用alpha值設定"
    L["Apply alpha when targeted"] = "圖騰為目標時套用alpha值"
    L["Always applies alpha, even when you target the totem. Else it is 1."] = "圖騰被選為目標時，其圖示套用alpha值設定"
    L["All totem border alphas (configurable per totem)"] = "圖騰 Alpha值 "
    L["Totem icon border style"] = "圖騰邊框樣式"
    L["All totem border color"] = "圖騰邊框顏色"

    -- Trinket.lua
    L["Trinket"] = "飾品"
    L["Enable trinket icon"] = "啟用飾品圖示"
    L["This changes positions of the trinket"] = "調整飾品圖示位置"

    -- XiconProfiles.lua
    L["Profile"] = "樣式"
    L["XiconProfiles"] = "框架外觀" --Line 4
    L[" No Pet"] = "(無寵物)" --Line 109, 119

    -- Frame.lua
    L["Gladdy - drag to move"] = "Gladdy - 拖曳移動"

    -- Gladdy.lua
    L["Welcome to Gladdy!"] = "歡迎使用 Gladdy!"
    L["First run has been detected, displaying test frame."] = "第一次使用時，顯示此測試框架。"
    L["Valid slash commands are:"] = "可用的指令為:"
    L["If this is not your first run please lock or move the frame to prevent this from happening."] = "若非第一次使用，請移動或鎖定框架以避免此提示再次出現。"

    -- Clicks.lua
    L["Action #%d"] = "動作 #%d"
    L["Target"] = "目標" --Line 15
    L["Focus"] = "專注" --Line 16
    L["Clicks"] = "點擊動作"
    L["Left button"] = "左鍵"
    L["Right button"] = "右鍵"
    L["Middle button"] = "中鍵"
    L["Button 4"] = "滑鼠按鍵4"
    L["Button 5"] = "滑鼠按鍵5"
    L["Select what action this mouse button does"] = "設定輸入按鍵後的欲執行的動作"
    L["Modifier"] = "修飾鍵"
    L["Select which modifier to use"] = "設定欲使用的修飾鍵"
    L["Button"] = "按鍵"
    L["Select which mouse button to use"] = "設定欲使用的滑鼠按鍵"
    L["Name"] = "名稱"
    L["Select the name of the click option"] = "設定動作名稱"
    L["Action"] = "動作"
    L["Cast Spell / Macro"] = "施放法術/巨集"

    --RangeCheck.lua
    L["Range Check"] = "距離檢查"
    L["Spells"] = "法術"
    L["Fade"] = "變暗"
    L["Out of Range Darkening Level"] = "超出距離時變暗程度"
    L["Higher is darker"] = "數值越高越暗"
    L["yds"] = " 碼" --Line 366, 388
    L["Changing the spellID only applies to your player class!\n\nExample: If you are a Paladin and wish to change your range check spell to Repentance, edit the Paladin spellID to 20066."] = "對應您的職業修改欲用於監控距離的技能。\n\n範例:若您為聖騎士且想以懺悔技能用於距離監控，請將聖騎士的法術ID改為20066。" --Line 352

    --ShadowsightTimer.lua
    L["Shadowsight Timer"] = "暗影視界計時"
    L["Locked"] = "鎖定"
    L["Announce"] = "通報"
    L["Scale"] = "大小"
    L["Shadowsight up in %ds"] = "暗影視界於%d秒後就緒"
    L["Shadowsight up!"] = "暗影視界已就緒"

    -- Options.lua
    L["settings"] = "設定"
    L["Reset module"] = "重設模組"
    L["Reset module to defaults"] = "將模組重設為預設值"
    L["No settings"] = "無設定"
    L["Module has no settings"] = "模組沒有設定"
    L["General settings"] = "通用設定"
    L["Lock frame"] = "鎖定框架"
    L["Toggle if frame can be moved"] = "調整框架是否可移動"
    L["Grow frame upwards"] = "框架向上延伸"
    L["If enabled the frame will grow upwards instead of downwards"] = "開啟此選項時框架向上延伸"
    L["Down"] = "下"
    L["Up"] = "上"
    L["Frame General"] = "框架"
    L["Frame scale"] = "框架大小"
    L["Scale of the frame"] = "框架的尺寸"
    L["Frame padding"] = "框架內距"
    L["Padding of the frame"] = "框架的內距"
    L["Frame width"] = "框架寬度"
    L["Margin"] = "框架間距"
    L["Margin between each button"] = "框架的間距"
    L["Cooldown General"] = "冷卻"
    L["Font General"] = "字型"
    L["General Font"] = "Allgemeine Schriftart"
    L["Font color text"] = "文字顏色"
    L["Font color timer"] = "計時器文字顏色"
    L["Color of the timers"] = "計時器顏色"
    L["Icons General"] = "圖示"
    L["Icon border style"] = "圖示邊框樣式"
    L["This changes the border style of all icons"] = "調整所有圖示的邊框樣式"
    L["This changes the border color of all icons"] = "調整所有圖示的邊框顏色"
    L["Statusbar General"] = "狀態列"
    L["Statusbar texture"] = "狀態列材質"
    L["This changes the texture of all statusbar frames"] = "調整所有狀態列的材質"
    L["Statusbar border style"] = "狀態列邊框樣式"
    L["This changes the border style of all statusbar frames"] = "調整所有狀態列的邊框樣式"
    L["Statusbar border offset divider (smaller is higher offset)"] = "狀態列邊框距離"
    L["Offset of border to statusbar (in case statusbar shows beyond the border)"] = "調整狀態列邊框距離"
    L["Statusbar border color"] = "狀態列邊框顏色"
    L["This changes the border color of all statusbar frames"] = "調整所有狀態列的邊框顏色"
    L["Hide Blizzard"] = "隱藏暴雪框架"
    L["Grow Direction"] = "框架延伸方向"
    L["Arena only"] = "只在競技場中"
    L["Never"] = "從不"
    L["Always"] = "永遠"
    L["Load configuration"] = "設定選項" --Line 713
    L["Load configuration options"] = "載入設定選項" --Line 714
    L["Background Color of the frame"] = "框架的背景顏色"

    L["Gladdy"] = "Gladdy目標框架"  --Line 210, 709, 727
end



-- Superhack allowing use key as value if not present in table
LibStub("Gladdy").L = setmetatable(L, {
    __index = function(t, k)
        return k
    end
})