local setmetatable = setmetatable

local GetLocale = GetLocale

local L = {}

if (GetLocale() == "ruRU") then
    -- Races
    L["Human"] = "Человек"
    L["Dwarf"] = "Дворф"
    L["Night Elf"] = "Ночной эльф"
    L["Gnome"] = "Гном"
    L["Draenei"] = "Дреней"
    L["Orc"] = "Орк"
    L["Undead"] = "Нежить"
    L["Tauren"] = "Таурен"
    L["Troll"] = "Тролль"
    L["Blood Elf"] = "Эльф крови"

    -- Classes
    L["Druid"] = "Друид"
    L["Hunter"] = "Охотник"
    L["Mage"] = "Маг"
    L["Paladin"] = "Паладин"
    L["Priest"] = "Жрец"
    L["Rogue"] = "Разбойник"
    L["Shaman"] = "Шаман"
    L["Warlock"] = "Чернокнижник"
    L["Warrior"] = "Воин"

    -- Specs
    L["Balance"] = "Баланс"
    L["Feral"] = "Сила зверя"
    L["Restoration"] = "Исцеление"
    L["Beast Mastery"] = "Повелитель зверей"
    L["Marksmanship"] = "Стрельба"
    L["Survival"] = "Выживание"
    L["Arcane"] = "Тайная магия"
    L["Fire"] = "Огонь"
    L["Frost"] = "Лед"
    L["Holy"] = "Свет"
    L["Protection"] = "Защита"
    L["Retribution"] = "Возмездие"
    L["Discipline"] = "Послушание"
    L["Shadow"] = "Тьма"
    L["Assassination"] = "Ликвидация"
    L["Combat"] = "Бой"
    L["Subtlety"] = "Скрытность"
    L["Elemental"] = "Cтихии"
    L["Enhancement"] = "Совершенствование"
    L["Affliction"] = "Колдовство"
    L["Demonology"] = "Демонология"
    L["Destruction"] = "Разрушение"
    L["Arms"] = "Оружие"
    L["Fury"] = "Неистовство"

    -- Gladdy.lua
    L["Welcome to Gladdy!"] = "Вас приветствует Gladdy!"
    L["First run has been detected, displaying test frame."] = "Обнаружен первый запуск, показываем тестовое окно."
    L["Valid slash commands are:"] = "Валидные команды:"
    L["If this is not your first run please lock or move the frame to prevent this from happening."] = "Если это не первый запуск, переместите, либо закрепите окно во избежание показа окна."

    -- Frame.lua
    L["Gladdy - drag to move"] = "Gladdy - тащите для перемещения"

    -- Options.lua
    L["Announcements"] = "Оповещения"
    L["Announcement settings"] = "Настройки оповещения"
    L["Auras"] = "Ауры"
    L["Auras settings"] = "Настройки аур"
    L["Castbar"] = "Полоса применения"
    L["Castbar settings"] = "Настройки полосы применения"
    L["Classicon"] = "Иконка класса"
    L["Classicon settings"] = "Настройки иконки класса"
    L["Clicks"] = "Клики"
    L["Clicks settings"] = "Настройки кликов"
    L["Diminishings"] = "Диминишинги"
    L["Diminishings settings"] = "Настройки диминишингов"
    L["Healthbar"] = "Полоса жизней"
    L["Healthbar settings"] = "Настройки полосы жизней"
    L["Highlight"] = "Подсветка"
    L["Highlight settings"] = "Настройки подсветки"
    L["Nameplates"] = "Индикаторы здоровья"
    L["Nameplates settings"] = "Настройки индикаторов здоровья "
    L["Powerbar"] = "Полоса маны"
    L["Powerbar settings"] = "Настройки полосы маны"
    L["Score"] = "Счет"
    L["Score settings"] = "Настройки счета"
    L["Trinket"] = "Тринкет"
    L["Trinket settings"] = "Настройки тринкета"
    L["Reset module"] = "Сбросить настройки"
    L["Reset module to defaults"] = "Сбросить настройки модуля к начальным"
    L["No settings"] = "Нет настроек"
    L["Module has no settings"] = "Модуль не имеет настроек"
    L["General"] = "Основные"
    L["General settings"] = "Основные настройки"
    L["Lock frame"] = "Закрепить фрейм"
    L["Toggle if frame can be moved"] = "Включите, если фрейм можно двигать"
    L["Grow frame upwards"] = "Расти вверх"
    L["If enabled the frame will grow upwards instead of downwards"] = "Если включено, то фрейм будет расти вверх, а не вниз"
    L["Frame scale"] = "Масштаб фрейма"
    L["Scale of the frame"] = "Масштаб фрейма"
    L["Frame padding"] = "Отступы фрейма"
    L["Padding of the frame"] = "Отступы фрейма"
    L["Frame color"] = "Цвет фрейма"
    L["Color of the frame"] = "Цвет фрейма"
    L["Bar width"] = "Ширина полос"
    L["Width of the bars"] = "Ширина полос"
    L["Bottom margin"] = "Нижняя граница полосы"
    L["Margin between each button"] = "Отступ до следующей полосы"

    -- Announcements.lua
    L["RESURRECTING: %s (%s)"] = "ВОСКРЕШАЕТ: %s (%s)"
    L["SPEC DETECTED: %s - %s (%s)"] = "СПЕЦИАЛИЗАЦИЯ ОПРЕДЕЛЕНА: %s - %s (%s)"
    L["LOW HEALTH: %s (%s)"] = "МАЛО ЗДОРОВЬЯ: %s (%s)"
    L["TRINKET USED: %s (%s)"] = "ТРИНКЕТ ИСПОЛЬЗОВАН: %s (%s)"
    L["TRINKET READY: %s (%s)"] = "ТРИНКЕТ ГОТОВ: %s (%s)"
    L["DRINKING: %s (%s)"] = "ПЬЁТ: %s (%s)"
    L["Self"] = "Сам"
    L["Party"] = "Группа"
    L["Raid Warning"] = "Объявление рейду"
    L["Blizzard's Floating Combat Text"] = "Стандартный текст боя"
    L["MikScrollingBattleText"] = "MikScrollingBattleText"
    L["Scrolling Combat Text"] = "Scrolling Combat Text"
    L["Parrot"] = "Parrot"
    L["Drinking"] = "Питьё"
    L["Announces when enemies sit down to drink"] = "Оповещать, когда вражеский игрок начинает пить"
    L["Resurrection"] = "Воскрешение"
    L["Announces when an enemy tries to resurrect a teammate"] = "Оповещать, когда вражеский игрок начинает воскрешать союзника"
    L["New enemies"] = "Новые враги"
    L["Announces when new enemies are discovered"] = "Оповещать о найденных вражеских игроках"
    L["Spec Detection"] = "Обнаружение специализации"
    L["Announces when the spec of an enemy was detected"] = "Оповещать, когда обнаружена специализация вражеского игрока"
    L["Low health"] = "Мало жизней"
    L["Announces when an enemy drops below a certain health threshold"] = "Оповещать, когда уровень здоровья вражеского игрока падает ниже определенного количества"
    L["Low health threshold"] = "Процент малого количества здоровья"
    L["Choose how low an enemy must be before low health is announced"] = "Укажите процент здоровья вражеского игрока, когда нужно показать оповещение"
    L["Trinket used"] = "Использование пвп-тринкета"
    L["Announce when an enemy's trinket is used"] = "Оповещать об использовании пвп-тринкета вражеским игроком"
    L["Trinket ready"] = "Готовность пвп-тринкета"
    L["Announce when an enemy's trinket is ready again"] = "Оповещать, когда пвп-тринкет вражеского игрока готов"
    L["Destination"] = "Вариант оповещений"
    L["Choose how your announcements are displayed"] = "Выберать, как показывать оповещения"

    -- Auras.lua
    L["Font color"] = "Цвет текста"
    L["Color of the text"] = "Цвет текста"
    L["Font size"] = "Размер текста"
    L["Size of the text"] = "Размер текста"

    -- Castbar.lua
    L["Bar height"] = "Высота полосы"
    L["Height of the bar"] = "Высота полосы"
    L["Bar texture"] = "Текстура полосы"
    L["Texture of the bar"] = "Текстура полосы"
    L["Bar color"] = "Цвет полосы"
    L["Color of the cast bar"] = "Цвет полосы применений"
    L["Background color"] = "Цвет фона полосы"
    L["Color of the cast bar background"] = "Цвет фона полосы применений"
    L["Icon position"] "Расположение значка трансляции"

    -- Clicks.lua
    L["Action #%d"] = "Действие #%d"
    L["Left Click Enemy 1"] = "Левый клик по цели 1"
    L["Left Click Enemy 2"] = "Левый клик по цели 2"
    L["Left Click Enemy 3"] = "Левый клик по цели 3"
    L["Left Click Enemy 4"] = "Левый клик по цели 4"
    L["Left Click Enemy 5"] = "Левый клик по цели 5"
    L["Right Click Enemy 1"] = "Правый клик по цели 1"
    L["Right Click Enemy 2"] = "Правый клик по цели 2"
    L["Right Click Enemy 3"] = "Правый клик по цели 3"
    L["Right Click Enemy 4"] = "Правый клик по цели 4"
    L["Right Click Enemy 5"] = "Правый клик по цели 5"
    L["Left button"] = "Левая кнопка"
    L["Right button"] = "Правая кнопка"
    L["Middle button"] = "Средняя кнопка"
    L["Button 4"] = "Кнопка 4"
    L["Button 5"] = "Кнопка 5"
    L["None"] = "Не назначено"
    L["CTRL"] = "CTRL"
    L["SHIFT"] = "SHIFT"
    L["ALT"] = "ALT"
    L["Cast Spell"] = "Применить заклинание"
    L["Name"] = "Название"
    L["Select the name of the click option"] = "Выбрать название опции клика"
    L["Button"] = "Кнопка"
    L["Select which mouse button to use"] = "Выбрать кнопку мыши для использования"
    L["Modifier"] = "Модификатор"
    L["Select which modifier to use"] = "Выбрать модификатор для использования"
    L["Action"] = "Действите"
    L["Select what action this mouse button does"] = "Выбрать действие, производимое данной кнопкой мыши"
    L["Spell name / Macro text"] = "Название заклинания / Текст макроса"
    L["Use *name* as unit's name. Like a '/rofl *name*'"] = "Используйте *name* в качестве имени игрока. Например, '/rofl *name*'"

    -- Diminishings.lua
    L["DR Cooldown position"] = "Позиция ДР таймеров"
    L["Position of the cooldown icons"] = "Позиция ДР таймеров"
    L["Left"] = "Слева"
    L["Right"] = "Справа"
    L["Icon Size"] = "Размер иконок"
    L["Size of the DR Icons"] = "Размер ДР иконок"

    -- Healthbar.lua
    L["Show the actual health"] = "Показывать текущее здоровье"
    L["Show the actual health on the health bar"] = "Показывать текущее здоровье на полосе жизней"
    L["Show max health"] = "Показывать максимальное здоровье"
    L["Show max health on the health bar"] = "Показывать максимальное здоровье на полосе жизней"
    L["Show health percentage"] = "Показывать здоровье в процентах"
    L["Show health percentage on the health bar"] = "Показывать здоровье в процентах на полосе жизней"

    -- Highlight.lua
    L["Border size"] = "Размер границы"
    L["Target border color"] = "Цвет контура цели"
    L["Color of the selected targets border"] = "Цвет контура цели"
    L["Focus border color"] = "Цвет контура фокуса"
    L["Color of the focus border"] = "Цвет контура фокуса"
    L["Raid leader border color"] = "Цвет контура цели рейд лидера"
    L["Color of the raid leader border"] = "Цвет контура цели рейд лидера"
    L["Highlight target"] = "Подсвечивать цель"
    L["Toggle if the selected target should be highlighted"] = "Включите, если необходима подсветка цели"
    L["Show border around target"] = "Показывать контур вокруг цели"
    L["Toggle if a border should be shown around the selected target"] = "Включите, если необходимо показывать контур вокруг цели"
    L["Show border around focus"] = "Показывать контур вокруг фокуса"
    L["Toggle of a border should be shown around the current focus"] = "Включите, если необходимо показывать контур вокруг фокуса"
    L["Show border around raid leader"] = "Показывать контур вокруг цели рейд лидера"
    L["Toggle if a border should be shown around the raid leader"] = "Включите, если необходимо показывать контур вокруг цели рейд лидера"

    -- Powerbar.lua
    L["Show the actual power"] = "Показывать текущую ману"
    L["Show the actual power on the power bar"] = "Показывать текущую ману на полосе маны"
    L["Show max power"] = "Показывать максимальную ману"
    L["Show max power on the power bar"] = "Показывать максимальную ману на полосе маны"
    L["Show power percentage"] = "Показывать ману в процентах"
    L["Show power percentage on the power bar"] = "Показывать ману в процентах на полосе маны"
    L["Color of the status bar background"] = "Цвет фона строки состояния"

    -- Trinket.lua
    L["No cooldown count (OmniCC)"] = "Не показывать кулдаун (OmniCC)"
    L["Disable cooldown timers by addons (reload UI to take effect)"] = "Отключить таймер кулдаунов для аддонов (необходима перезагрузка интерфейса)"
elseif (GetLocale() == "deDE") then
    -- Races
    L["Human"] = "Mensch"
    L["Dwarf"] = "Zwerg"
    L["Night Elf"] = "Nachtelf"
    L["Gnome"] = "Gnom"
    L["Draenei"] = "Draenei"
    L["Orc"] = "Ork"
    L["Undead"] = "Untoter"
    L["Tauren"] = "Taure"
    L["Troll"] = "Тroll"
    L["Blood Elf"] = "Blutelf"

    -- Classes
    L["Druid"] = "Druide"
    L["Hunter"] = "Jäger"
    L["Mage"] = "Magier"
    L["Paladin"] = "Paladin"
    L["Priest"] = "Priester"
    L["Rogue"] = "Schurke"
    L["Shaman"] = "Schamane"
    L["Warlock"] = "Hexenmeister"
    L["Warrior"] = "Krieger"

    -- Specs
    L["Balance"] = "Gleichgewicht"
    L["Feral"] = "Wilder Kampf"
    L["Restoration"] = "Wiederherstellung"
    L["Beast Mastery"] = "Tierherrschaft"
    L["Marksmanship"] = "Treffsicherheit"
    L["Survival"] = "Überleben"
    L["Arcane"] = "Arkan"
    L["Fire"] = "Feuer"
    L["Frost"] = "Frost"
    L["Holy"] = "Heilig"
    L["Protection"] = "Schutz"
    L["Retribution"] = "Vergeltung"
    L["Discipline"] = "Disziplin"
    L["Shadow"] = "Schatten"
    L["Assassination"] = "Meucheln"
    L["Combat"] = "Kampf"
    L["Subtlety"] = "Täuschung"
    L["Elemental"] = "Elemental"
    L["Enhancement"] = "Verstärkung"
    L["Affliction"] = "Gebrechen"
    L["Demonology"] = "Demonologie"
    L["Destruction"] = "Zerstörung"
    L["Arms"] = "Waffen"
    L["Fury"] = "Furor"

    -- Gladdy.lua
    L["Welcome to Gladdy!"] = "Willkommen bei Gladdy!"
    L["First run has been detected, displaying test frame."] = "Erster Start wurde entdeckt, zeige Testbild an."
    L["Valid slash commands are:"] = "Gültige slash Befehle sind:"
    L["If this is not your first run please lock or move the frame to prevent this from happening."] = "Wenn dies nicht dein erster Start ist, sperre oder bewege das Bild um diese Meldung zu verhindern."

    -- Frame.lua
    L["Gladdy - drag to move"] = "Gladdy - ziehe um zu bewegen"

    -- Options.lua
    L["Announcements"] = "Meldungen"
    L["Announcement settings"] = "Meldungseinstellungen"
    L["Auras"] = "Auren"
    L["Auras settings"] = "Aureneinstellungen"
    L["Castbar"] = "Zauberleiste"
    L["Castbar settings"] = "Zauberleisteneinstellungen"
    L["Classicon"] = "Klassensymbol"
    L["Classicon settings"] = "Klassensymboleinstellungen"
    L["Clicks"] = "Klicks"
    L["Clicks settings"] = "Klickeinstellungen"
    L["Diminishings"] = "DR"
    L["Diminishings settings"] = "DR Einstellungen"
    L["Healthbar"] = "Lebensleiste"
    L["Healthbar settings"] = "Lebensleisteneinstellungen"
    L["Highlight"] = "warnung"
    L["Highlight settings"] = "Warnungseinstellungen"
    L["Nameplates"] = "Namensplaketten"
    L["Nameplates settings"] = "Namensplaketteneinstellungen"
    L["Powerbar"] = "Powerleiste"
    L["Powerbar settings"] = "Powerleisteneinstellungen"
    L["Score"] = "Score"
    L["Score settings"] = "Scoreeinstellungen"
    L["Trinket"] = "Insignie"
    L["Trinket settings"] = "Insignieneinstellungen"
    L["Reset module"] = "Model zurücksetzen"
    L["Reset module to defaults"] = "Modul auf Standardeinstellungen zurücksetzen"
    L["No settings"] = "Keine Einstellungen"
    L["Module has no settings"] = "Modul hat keine Einstellungen"
    L["General"] = "ОAllgemein"
    L["General settings"] = "Allgemeine Einstellungen"
    L["Lock frame"] = "Sperre Bild"
    L["Toggle if frame can be moved"] = "Aktivieren falls das Bild bewegt werden kann"
    L["Grow frame upwards"] = "Bild von unten nach oben aufbauen"
    L["If enabled the frame will grow upwards instead of downwards"] = "Falls aktiviert, wird das Bild von unten nach oben aufgebaut"
    L["Frame scale"] = "Bildskalierung"
    L["Scale of the frame"] = "Skalierung des Bildes"
    L["Frame padding"] = "Bild Unterlage"
    L["Padding of the frame"] = "Unterlage des Bildes"
    L["Frame color"] = "Bildfarbe"
    L["Color of the frame"] = "Farbe des Bildes"
    L["Bar width"] = "Leistenbreite"
    L["Width of the bars"] = "Breite der Leisten"
    L["Bottom margin"] = "Unterer Abstand"
    L["Margin between each button"] = "Abstand zwischen jedem Buttom"

    -- Announcements.lua
    L["RESURRECTING: %s (%s)"] = "Wiederbeleben: %s (%s) "
    L["SPEC DETECTED: %s - %s (%s)"] = "Talenspezalisierung entdeckt: %s - %s (%s)"
    L["LOW HEALTH: %s (%s)"] = "Niedriges Leben: %s (%s)"
    L["TRINKET USED: %s (%s)"] = "Insiginie benutzt: %s (%s)"
    L["TRINKET READY: %s (%s)"] = "Insignie bereit: %s (%s)"
    L["DRINKING: %s (%s)"] = "Trinken: %s (%s)"
    L["Self"] = "Selbst"
    L["Party"] = "Gruppe"
    L["Raid Warning"] = "Schlachtzugwarnung"
    L["Blizzard's Floating Combat Text"] = "Blizzard Kampftext"
    L["MikScrollingBattleText"] = "MikScrollingBattleText"
    L["Scrolling Combat Text"] = "Scrolling Combat Text"
    L["Parrot"] = "Parrot"
    L["Drinking"] = "Trinken"
    L["Announces when enemies sit down to drink"] = "Warnt wenn Gegner sich zum Trinken hinsetzen"
    L["Resurrection"] = "Wiederbelebung"
    L["Announces when an enemy tries to resurrect a teammate"] = "Warnt wenn Gegner versuchen Teammitglieder wiederzubeleben"
    L["New enemies"] = "Neue Gegner"
    L["Announces when new enemies are discovered"] = "Gibt an, wenn neue Gegner entdeckt wurden"
    L["Spec Detection"] = "Talent Entdeckung"
    L["Announces when the spec of an enemy was detected"] = "Gibt an, wenn Talente eines Gegners entdeckt wurden"
    L["Low health"] = "Wenig Leben"
    L["Announces when an enemy drops below a certain health threshold"] = "Warnt, wenn das Leben eines Gegners unter einen bestimmten Prozentwert fällt"
    L["Low health threshold"] = "Prozentwert: Wenig Leben"
    L["Choose how low an enemy must be before low health is announced"] = "Bestimme wie wenig Leben ein Gegner haben muss, damit vor wenig Leben gewarnt wird"
    L["Trinket used"] = "Insignie benutzt"
    L["Announce when an enemy's trinket is used"] = "Warnt, wenn ein Gegner seine Insignie benutzt"
    L["Trinket ready"] = "Insignie bereit"
    L["Announce when an enemy's trinket is ready again"] = "Warnt wenn die Insignie eines Gegner wieder bereit ist"
    L["Destination"] = "Ziel"
    L["Choose how your announcements are displayed"] = "Bestimme wo Warnungen dargestellt werden"

    -- Auras.lua
    L["Font color"] = "Schriftfarbe"
    L["Color of the text"] = "Farbe der Schrift"
    L["Font size"] = "Schriftgröße"
    L["Size of the text"] = "Größe der Schrift"

    -- Castbar.lua
    L["Bar height"] = "Leistenhöhe"
    L["Height of the bar"] = "Höhe der Leiste"
    L["Bar texture"] = "Leistentextur"
    L["Texture of the bar"] = "Textur der Leiste"
    L["Bar color"] = "Leistenfarbe"
    L["Color of the cast bar"] = "Farbe der Zauberleiste"
    L["Background color"] = "Hintergrundfarbe"
    L["Color of the cast bar background"] = "Hintergrundfarbe der Zauberleiste"
    L["Icon position"] "Position des Zauberleistensymbols"

    -- Clicks.lua
    L["Action #%d"] = "Aktion #%d"
    L["Left Click Enemy 1"] = "Linksklick Gegner 1"
    L["Left Click Enemy 2"] = "Linksklick Gegner 2"
    L["Left Click Enemy 3"] = "Linksklick Gegner 3"
    L["Left Click Enemy 4"] = "Linksklick Gegner 4"
    L["Left Click Enemy 5"] = "Linksklick Gegner 5"
    L["Right Click Enemy 1"] = "Rechtsklick Gegner 1"
    L["Right Click Enemy 2"] = "Rechtsklick Gegner 2"
    L["Right Click Enemy 3"] = "Rechtsklick Gegner 3"
    L["Right Click Enemy 4"] = "Rechtsklick Gegner 4"
    L["Right Click Enemy 5"] = "Rechtsklick Gegner 5"
    L["Left button"] = "Linke Taste"
    L["Right button"] = "Rechte Taste"
    L["Middle button"] = "Mittlere Taste"
    L["Button 4"] = "Maus 4"
    L["Button 5"] = "Maus 5"
    L["None"] = "Keine"
    L["CTRL"] = "STRG"
    L["SHIFT"] = "SHIFT"
    L["ALT"] = "ALT"
    L["Cast Spell"] = "Wirke Zauber"
    L["Name"] = "Name"
    L["Select the name of the click option"] = "Wähle einen Namen für die Klickoption"
    L["Button"] = "Taste"
    L["Select which mouse button to use"] = "Wähle welche Maustaste genutzt werden soll"
    L["Modifier"] = "Modifier"
    L["Select which modifier to use"] = "Wähle welcher Modifier benutzt werdne soll"
    L["Action"] = "Aktion"
    L["Select what action this mouse button does"] = "Wähle welche Aktion die Maustaste durchführt"
    L["Spell name / Macro text"] = "Zaubername / Makrotext"
    L["Use *name* as unit's name. Like a '/rofl *name*'"] = "Benutzt *name* als Gegnername. Zum Beispiel '/rofl *name*'"

    -- Diminishings.lua
    L["DR Cooldown position"] = "Position des DR Cooldowns"
    L["Position of the cooldown icons"] = "Position des DR Cooldowns"
    L["Left"] = "Links"
    L["Right"] = "Rechts"
    L["Icon Size"] = "Symbolgröße"
    L["Size of the DR Icons"] = "Größe des DR Symbols"

    -- Healthbar.lua
    L["Show the actual health"] = "Zeige das Leben an"
    L["Show the actual health on the health bar"] = "Zeige das Leben auf der Lebensanzeige an"
    L["Show max health"] = "Zeige Maximalleben an"
    L["Show max health on the health bar"] = "Zeige Maximalleben auf der Lebensanzeige an"
    L["Show health percentage"] = "Zeige prozentuales Leben"
    L["Show health percentage on the health bar"] = "Zeige prozentuales Leben auf der Lebensanzeige an"

    -- Highlight.lua
    L["Border size"] = "Rahmengröße"
    L["Target border color"] = "Zielrahmenfarbe"
    L["Color of the selected targets border"] = "Farbe des Rahmens des gewählten Ziels"
    L["Focus border color"] = "Focusrahmenfarbe"
    L["Color of the focus border"] = "Farbe des Focusrahmens"
    L["Raid leader border color"] = "Schlachtzugleiterrahmenfarbe"
    L["Color of the raid leader border"] = "Farbe des Rahmens für den Schlachtzugleiter"
    L["Highlight target"] = "Highlight Ziel"
    L["Toggle if the selected target should be highlighted"] = "Включите, если необходима подсветка цели"
    L["Show border around target"] = "Zeige Rahmen um das Ziel an"
    L["Toggle if a border should be shown around the selected target"] = "Auswählen wenn ein Ramhen um das ausgewählte Ziel angezeigt werden soll"
    L["Show border around focus"] = "Zeige Rahmen um Focus"
    L["Toggle of a border should be shown around the current focus"] = "Auswählen wenn ein Ramhen um das ausgewählte Focusziel angezeigt werden soll"
    L["Show border around raid leader"] = "Zeige Rahmen um Schlachtzugleiter"
    L["Toggle if a border should be shown around the raid leader"] = "Auswählen wenn ein Ramhen um den ausgewählten SChlachtzugleiter angezeigt werden soll"

    -- Powerbar.lua
    L["Show the actual power"] = "Zeige genaue Power"
    L["Show the actual power on the power bar"] = "Zeige die genaue Power in der Powerleiste "
    L["Show max power"] = "Zeige Maximalpower"
    L["Show max power on the power bar"] = "Zeige Maximalpower in der Powerbau"
    L["Show power percentage"] = "Zeige prozentuale Power"
    L["Show power percentage on the power bar"] = "Zeige prozentuale Power in der Powerbau"
    L["Color of the status bar background"] = "Hintergrundfarbe der Statusleiste"

    -- Trinket.lua
    L["No cooldown count (OmniCC)"] = "Keine Cooldownanzeige (OmniCC)"
    L["Disable cooldown timers by addons (reload UI to take effect)"] = "Deaktiviere Cooldownanzeige durch Addons (UI neu laden um zu wirken)"
end

-- Superhack allowing use key as value if not present in table
LibStub("Gladdy").L = setmetatable(L, {
    __index = function(t, k)
        return k
    end
})